version: '2'
services:
    savemeapp-app:
        image: savemeapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://savemeapp-mysql:3306/savemeapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    savemeapp-mysql:
        extends:
            file: mysql.yml
            service: savemeapp-mysql
